server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    wait-time-in-ms-when-sync-empty: 5